# Generated by Django 3.1.7 on 2021-03-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210328_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
