# Generated by Django 3.1.7 on 2021-03-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
