# Generated by Django 3.1.7 on 2021-03-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210329_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
